CREATE TABLE IF NOT EXISTS bronze_all_activity (
    id BIGINT PRIMARY KEY, 
    achievement_count INTEGER, 
    athlete JSONB, 
    athlete_count INTEGER, 
    average_speed NUMERIC, 
    average_watts NUMERIC, 
    comment_count INTEGER, 
    commute BOOLEAN, 
    device_watts BOOLEAN,
    distance NUMERIC, 
    elapsed_time INTEGER, 
    elev_high NUMERIC, 
    elev_low NUMERIC, 
    end_latlng NUMERIC[2], 
    external_id TEXT, 
    flagged BOOLEAN, 
    gear_id TEXT, 
    has_kudoed BOOLEAN, 
    hide_from_home BOOLEAN, 
    kilojoules NUMERIC, 
    kudos_count INTEGER, 
    "manual" BOOLEAN, 
    map JSONB, 
    max_speed NUMERIC, 
    max_watts INTEGER,
    moving_time INTEGER, 
    "name" TEXT, 
    photo_count INTEGER, 
    "private" BOOLEAN, 
    sport_type TEXT, -- define enum
    "start_date" TIMESTAMPTZ, 
    start_date_local TIMESTAMPTZ, 
    start_latlng NUMERIC[2], 
    timezone TEXT, 
    total_elevation_gain NUMERIC, 
    total_photo_count INTEGER, 
    trainer BOOLEAN, 
    "type" TEXT, 
    upload_id BIGINT, 
    upload_id_str TEXT, 
    weighted_average_watts INTEGER, 
    workout_type INTEGER, 
    utc_offset NUMERIC, 
    location_city TEXT, 
    location_state TEXT, 
    location_country TEXT, 
    pr_count INTEGER, 
    suffer_score INTEGER, 
    has_heartrate BOOLEAN, 
    average_heartrate NUMERIC, 
    max_heartrate INTEGER, 
    average_cadence NUMERIC, 
    from_accepted_tag BOOLEAN, 
    visibility TEXT, 
    ingested_at TIMESTAMPTZ DEFAULT NOW()
)