CREATE TABLE IF NOT EXISTS activities_silver (
    id                      BIGINT NOT NULL PRIMARY KEY,
    achievement_count       INTEGER,
    athlete_count           INTEGER,
    average_speed           DOUBLE PRECISION,
    average_watts           DOUBLE PRECISION,
    comment_count           INTEGER,
    distance                DOUBLE PRECISION,
    elapsed_time            INTEGER,
    elev_high               DOUBLE PRECISION,
    elev_low                DOUBLE PRECISION,
    external_id             TEXT,
    gear_id                 TEXT,
    kudos_count             INTEGER,
    max_speed               DOUBLE PRECISION,
    max_watts               DOUBLE PRECISION,
    moving_time             INTEGER,
    name                    TEXT,
    photo_count             INTEGER,
    sport_type              TEXT,
    start_date              TIMESTAMPTZ,
    start_date_local        TIMESTAMPTZ,
    timezone                TEXT,
    total_elevation_gain    DOUBLE PRECISION,
    total_photo_count       INTEGER,
    trainer                 BOOLEAN,
    upload_id               BIGINT,
    weighted_average_watts  DOUBLE PRECISION,
    pr_count                INTEGER,
    suffer_score            DOUBLE PRECISION,
    average_heartrate       DOUBLE PRECISION,
    max_heartrate           DOUBLE PRECISION,
    average_cadence         DOUBLE PRECISION,
    visibility              TEXT,
    ingested_at             TIMESTAMPTZ,
    athlete_id              BIGINT,
    end_lat                 DOUBLE PRECISION,
    end_lng                 DOUBLE PRECISION,
    start_lat               DOUBLE PRECISION,
    start_lng               DOUBLE PRECISION,
    map_polyline            TEXT
);
-- DROP TABLE IF EXISTS activities_silver;